-- 감사 로그가 계정을 참조하므로 삭제 대신 비활성화를 쓴다.
ALTER TABLE "User" ADD COLUMN "disabledAt" TIMESTAMP(3);

ALTER TYPE "AuditAction" ADD VALUE 'USER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_PASSWORD_RESET';
ALTER TYPE "AuditAction" ADD VALUE 'USER_SESSIONS_REVOKED';
